addons:
  apt:
    packages:
    - oracle-java8-installer
after_failure:
- util/print_surefire_reports.sh
after_success:
- util/deploy_snapshot.sh
- util/update_snapshot_docs.sh
before_cache:
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do
  du -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line
  $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
- cp /tmp/classpathFile $HOME/CACHE/classpathFile
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then sed -i '' 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        else sed -i 's/<gib.enabled>true/<gib.enabled>false/'
  $TRAVIS_BUILD_DIR/pom.xml;        fi
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
before_script:
- find $TRAVIS_BUILD_DIR -name .ekstazi | while read line; do rm -rf $line; done
- find $HOME/CACHE -name .ekstazi | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.ekstazi/} ]]; then cp -r $line $DIR; fi; done
- if [ "$TRAVIS_OS_NAME" == "osx" ];    then sed -i '' 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    else sed -i 's/<gib.enabled>false/<gib.enabled>true/'
  $TRAVIS_BUILD_DIR/pom.xml;    fi
- if [[ -e $HOME/CACHE/classpathFile ]]; then cp $HOME/CACHE/classpathFile /tmp/;
  fi
branches:
  only:
  - master
  - /^release.*$/
cache:
  directories:
  - $HOME/.m2
  - $HOME/CACHE
env:
  global:
  - secure: IPvqFwnLx/GXyImJuwM2MIvzDlBLqEXaQXFGJgAP1nbuenaLAloOOlqQ+iy2FDLBD/j+zjSbR3WWF9DIT4YxAS03Z6iMwxh7GCfk+tyhVtLQnwt7w1rquyhbrrGFsY5U0hr5q80Ww6J+zfp2yZ8aP9FHSy5ahNjqys4FtubOWLk=
  - secure: G77Wt2h2fceQ867i1uwOjUygrNeBpLRS8sxgfUZsO66dvlrx1wYFpZLLRIiPcy01peUTE2SvXIXLHKe9v3AlMonPibsQtvvfQSVfx+jgKwLZx9cuf/M5VQlD3etRUh4K/rBezlxWRroeeKcM2DQqiEVLsTDSyNZV9kVAjwfLTvM=
  - secure: wieIClPLTXS3QjDzqyp0TqIrVP/Q6iWNPOtcUQYfdDZJGwufE61laTFtzVKXZRb7uJ4GXDObcVU3AcpAwkTX/5sEksBxgv3TZ5Qi0mVx2GRmbE06ULLxi7sPnTCZ/VFtselDWcWArWGAcdCjW9gcCrgj5K/+sYpVKz9a8V+SDM4=
  matrix:
  - ROOT_POM="pom.xml"
  - ROOT_POM="android/pom.xml"
install: mvn -B install -U -DskipTests=true -f $ROOT_POM
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- travis_wait 60 mvn -B verify -U -Dmaven.javadoc.skip=true -f $ROOT_POM
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
